- name: Setup mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: present

- name: Updating mongodb listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '12.0.0.1'
    replace: '0.0.0.0'

- name: Starting mongodb
  ansible.bhuiltin.systemd:
    name: mongod
    state: started
    enable: true



