- name: Configure Nodejs Repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: present

- name: App pre-requisites
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Install nodejS Dependencies
#  community.general.npm:
#    path: /app
  ansible.builtin.shell: npm install
  args:
      chdir: /app

- name: Schema setup
  ansible.builtin.import_tasks:
    file: schema-setup.yml
  when: schema_type is defined

- name: Systemd setup
  ansible.builtin.import_tasks:
    file: systemd-setup.yml